# Generated by Django 3.1.14 on 2022-07-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_town_builder_nautobot_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='item_rarity',
            field=models.TextField(default='common'),
            preserve_default=False,
        ),
    ]
